## This is deployed by the operator to register the CSI Driver.
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.tkm.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
