apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: tkm-operator
    app.kubernetes.io/part-of: tkm-operator
    app.kubernetes.io/managed-by: tkm-operator
  name: tkm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkm-operator
  namespace: tkm
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: tkm-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: tkm-operator
    app.kubernetes.io/part-of: tkm-operator
    app.kubernetes.io/managed-by: tkm-operator
spec:
  selector:
    matchLabels:
      name: tkm-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      hostNetwork: false
      containers:
        - name: tkm-operator
          image: quay.io/billy99/tkm-operator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
